#include extensions.ivr.gui.conf
#include extensions.ringgroup.gui.conf
#include extensions.queue.gui.conf
#include extensions.paging.gui.conf
#include extensions.speed_dial.gui.conf
#include extensions.feature_codes.gui.conf
#include extensions.pickup_groups.gui.conf
#include extensions.announcement.gui.conf
