[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*SecurityEvent="ChallengeResponseFailed".*Service="PJSIP".*RemoteAddress="[A-Z0-9]+/(UDP|TCP|TLS)/<HOST>/[0-9]+".*$
            ^.*SecurityEvent="InvalidAccountID".*Service="PJSIP".*RemoteAddress="[A-Z0-9]+/(UDP|TCP|TLS)/<HOST>/[0-9]+".*$
            ^.*NOTICE.*res_pjsip/pjsip_distributor.c:.*Request 'REGISTER'.*failed for '<HOST>:[0-9]+'.*$

ignoreregex = ^.*SecurityEvent="ChallengeSent".*$
              ^.*SecurityEvent="SuccessfulAuth".*$
