[5000]
max_contacts=10
remove_existing=yes
qualify_frequency=60
type=aor

; rcm_max_contacts=10
maximum_expiration=120
[5001]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

; rcm_max_contacts=10
maximum_expiration=120
[5002]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

; rcm_max_contacts=10
maximum_expiration=120
[5004]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60
; rcm_max_contacts=10
maximum_expiration=120
[9999]
type=aor
max_contacts=9666
remove_existing=yes
qualify_frequency=60

; rcm_max_contacts=9666
maximum_expiration=120
[5858]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60
; rcm_max_contacts=10
maximum_expiration=120
[2121]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

; rcm_max_contacts=10
maximum_expiration=120
[3001]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

; rcm_max_contacts=10
maximum_expiration=120
[555]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

; rcm_max_contacts=10
maximum_expiration=120
[GSM]
type=aor
contact=sip:192.168.99.237:5060
qualify_frequency=60
maximum_expiration=3600
; --- RCM-TRUNK: GSM END ---

[4321]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120
; --- RCM-TRUNK: ucm1 BEGIN ---
[ucm1]
type=aor
contact=sip:192.168.99.17:5060
qualify_frequency=60
maximum_expiration=3600
; --- RCM-TRUNK: ucm1 END ---

[5555]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[5003]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[852]
type=aor
; rcm_max_contacts=10
max_contacts=10
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6000]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6001]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6002]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6003]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6004]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6005]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6006]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6007]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6008]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120

[6009]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120
; --- RCM-TRUNK: 6666 BEGIN ---
[6666-aor]
type=aor
contact=sip:6666@c074ad298964-10952.b.gdms.cloud:5061
qualify_frequency=60
maximum_expiration=3600
; --- RCM-TRUNK: 6666 END ---

[6100]
type=aor
; rcm_max_contacts=3
max_contacts=3
remove_existing=yes
qualify_frequency=60
maximum_expiration=120
