; --- RCM-TRUNK: 6666 BEGIN ---
[6666-reg]
type=registration
transport=transport-tls
outbound_auth=6666-auth
server_uri=sip:c074ad298964-10952.b.gdms.cloud:5061
client_uri=sip:6666@c074ad298964-10952.b.gdms.cloud:5061
contact_user=6666
endpoint=6666
line=yes
retry_interval=60
forbidden_retry_interval=600
expiration=3600
outbound_proxy=sip:c074ad298964-10952.b.gdms.cloud:5061\;lr
; --- RCM-TRUNK: 6666 END ---
