[5000]
type=auth
auth_type=userpass
username=5000
password=Abc@5000

[5001]
type=auth
auth_type=userpass
username=5001
password=Abc@1234

[5002]
type=auth
auth_type=userpass
username=5002
password=Abc@5002

[5004]
type=auth
auth_type=userpass
username=5004
password=Abc@5004
[9999]
type=auth
auth_type=userpass
username=9999
password=Abc@1234

[5858]
type=auth
auth_type=userpass
username=5858
password=Abc@1234

[2121]
type=auth
auth_type=userpass
username=2121
password=Abc@1234

[3001]
type=auth
auth_type=userpass
username=3001
password=Abc@1234

[555]
type=auth
auth_type=userpass
username=555
password=888

[4321]
type=auth
auth_type=userpass
username=4321
password=Abc@1234
[5555]
type=auth
auth_type=userpass
username=5555
password=Abc@1234

[5003]
type=auth
auth_type=userpass
username=5003
password=Abc@1234

[852]
type=auth
auth_type=userpass
username=852
password=Abc@1234

[6000]
type=auth
auth_type=userpass
username=6000
password=Abc@1234

[6001]
type=auth
auth_type=userpass
username=6001
password=Abc@1234

[6002]
type=auth
auth_type=userpass
username=6002
password=Abc@1234

[6003]
type=auth
auth_type=userpass
username=6003
password=Abc@1234

[6004]
type=auth
auth_type=userpass
username=6004
password=Abc@1234

[6005]
type=auth
auth_type=userpass
username=6005
password=Abc@1234

[6006]
type=auth
auth_type=userpass
username=6006
password=Abc@1234

[6007]
type=auth
auth_type=userpass
username=6007
password=Abc@1234

[6008]
type=auth
auth_type=userpass
username=6008
password=Abc@1234

[6009]
type=auth
auth_type=userpass
username=6009
password=Abc@1234
; --- RCM-TRUNK: 6666 BEGIN ---
[6666-auth]
type=auth
auth_type=userpass
username=6666
password=Abc@123456
; --- RCM-TRUNK: 6666 END ---

[6100]
type=auth
auth_type=userpass
username=6100
password=Abc@1234
