[2222]
type=aor
max_contacts=3
qualify_frequency=60

[2211]
type=aor
max_contacts=3
qualify_frequency=60



[2233]
type=aor
max_contacts=3
qualify_frequency=60

[2001]
type=aor
max_contacts=10                          ; Concurrent Registrations
remove_existing=yes                      ;كل جهاز يخلي الي قبله مش ريجستر
;qualify_frequency=30                    ; Keep-alive Frequency
;qualify_timeout=3.0                     ; يستني رد لمده 3 ثواني لو مردش يبقي مش شغال
;default_expiration=3600                         ; Max Expiration
qualify_frequency=60

[2200]
type=aor
max_contacts=3
qualify_frequency=60


[2002]
type=aor
max_contacts=3
qualify_frequency=60






;[feg4301]
;type=aor
;contact=sip:192.168.99.237:5060
;qualify_frequency=60



;[4444]
;type=aor
;contact=sip:192.168.99.243:5060
;qualify_frequency=60
;max_contacts=1
;remove_existing=yes


;[4444]
;type=aor
;max_contacts=1
;remove_existing=yes
;qualify_frequency=60


;[5600-aor]
;type=aor
;contact=sip:5600@192.168.99.9:5060
;qualify_frequency=3
