[auth2222]
type=auth
auth_type=userpass
username=2222
password=Abc@1234


[auth2211]
type=auth
auth_type=userpass
username=2211
password=Abc@1234



[auth2233]
type=auth
auth_type=userpass
username=2233
password=Abc@1234

[2001]
type=auth
auth_type=userpass
username=2001
password=Abc@1234

[auth2002]
type=auth
auth_type=userpass
username=2002
password=Abc@1234


[auth2200]
type=auth
auth_type=userpass
username=2200
password=Abc@1234




;[4444-auth]
;type=auth
;auth_type=userpass
;username=4444
;password=4444


;[4444-auth]
;type=auth
;auth_type=userpass
;username=4444
;password=4444


;[5600-auth]
;type=auth
;auth_type=userpass
;username=5600
;password=5600
