[2222]
type=endpoint
context=from-internal-2222
disallow=all
allow=ulaw
auth=auth2222
aors=2222
transport=transport-udp

[2211]
type=endpoint
context=from-internal-2211
disallow=all
allow=ulaw
auth=auth2211
aors=2211
transport=transport-udp


[2233]
type=endpoint
context=from-internal-2233
disallow=all
allow=ulaw
auth=auth2233
aors=2233
transport=transport-udp

[2001]
type=endpoint
context=from-internal-2001
disallow=all
allow=alaw,ulaw
aors=2001
auth=2001
transport=transport-udp
;direct_media=no                         ;direct media

[2002]
type=endpoint
context=from-internal-2002
disallow=all
allow=ulaw
auth=auth2002
aors=2002
transport=transport-udp

[2200]
type=endpoint
context=from-internal-2200
disallow=all
allow=ulaw
auth=auth2200
aors=2200
transport=transport-udp





;========================================================
;[[[[[[[[[[[[[[[[ BEER TRUNK ]]]]]]]]]]]]]]]]]]

;[feg4301]
;type=endpoint
;transport=transport-udp
;context=from-pri
;disallow=all
;allow=ulaw,alaw
;aors=feg4301




;[[[[[[[register trunk like grandstream   ]]]]]]]]
;[4444]
;type=endpoint
;transport=transport-udp
;context=from-trunk
;disallow=all
;allow=alaw,ulaw
;aors=4444
;auth=4444-auth



;[[[[[[[[[[[[[[[[[[[[[[[ Server mode Trunk ]]]]]]]]]]]]]]]]]]]]]]]]
;[4444]
;type=endpoint
;transport=transport-udp
;context=from-trunk
;disallow=all
;allow=alaw,ulaw
;aors=4444
;auth=4444-auth
;rewrite_contact=yes




;[[[[[[[[[[[[[[ clint mode trunk ]]]]]]]]]]]]]]]]]]]]]]]]]]

;[5600]
;type=endpoint
;context=from-trunk
;disallow=all
;allow=alaw,ulaw
;aors=5600-aor
;identify_by=auth_username



