; --- RCM-TRUNK: GSM BEGIN ---
[GSM_identify]
type=identify
endpoint=GSM
match=192.168.99.237
; --- RCM-TRUNK: GSM END ---
; --- RCM-TRUNK: ucm1 BEGIN ---
[ucm1_identify]
type=identify
endpoint=ucm1
match=192.168.99.17
; --- RCM-TRUNK: ucm1 END ---

; --- RCM-TRUNK: 6666 BEGIN ---
[6666-identify]
type=identify
endpoint=6666
match=c074ad298964-10952.b.gdms.cloud
; --- RCM-TRUNK: 6666 END ---
