;[5600-reg]
;type=registration                       ; روح اعمل ريجيستر علي سيرفر تاني
;outbound_auth=5600-auth                 ;لما يروح يعمل ريجيستر هيطلب منه يوزر و باسورد يروح يجيبهم من هناك
;server_uri=sip:192.168.99.9:5060        ; هيروح يريجستر علي ده بالبورت ده
;client_uri=sip:5600@192.168.99.9        ; اسم اليوزر الي انت هتروح بيهرر
;expiration=3600                         ;الوقت الي هو هيقعده علشان يبعت تاني ريجيستر
